;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Game/GameplayAbilitySystem/Tags/DT_WeaponPrimaryAttributeTags.DT_WeaponPrimaryAttributeTags
+GameplayTagRedirects=(OldTagName="Message.Pickup.HealingPotion",NewTagName="Message.Pickup.Healtgh")
+GameplayTagRedirects=(OldTagName="Message.Pickup.Healtgh",NewTagName="Message.Pickup.Health")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Message.Collection",DevComment="")
+GameplayTagList=(Tag="Message.Collection.Unlock",DevComment="")
+GameplayTagList=(Tag="Message.Collection.Unlock.Equipment",DevComment="")
+GameplayTagList=(Tag="Message.Collection.Unlock.Weapon",DevComment="")
+GameplayTagList=(Tag="Message.Collection.Unlock.Weapon.Bow1",DevComment="")
+GameplayTagList=(Tag="Message.Collection.Unlock.Weapon.Bow2",DevComment="")
+GameplayTagList=(Tag="Message.Pickup.DurationHealth",DevComment="")
+GameplayTagList=(Tag="Message.Pickup.Health",DevComment="")
+GameplayTagList=(Tag="Message.Pickup.Money",DevComment="")

